# Site settings
title: My Awesome Book
description: A website to showcase my new book
url: https://username.github.io
baseurl: ""

# Theme settings
theme: jekyll-theme-cayman

# Navigation menu
navbar_links:
  Home: "/"
  About: "/about"
  Blog: "/blog"
  Contact: "/contact"

# Social links
social_links:
  Twitter: "https://twitter.com/username"
  GitHub: "https://github.com/username"
  LinkedIn: "https://linkedin.com/in/username"

# Footer
footer_links:
  Privacy Policy: "/privacy"
  Terms of Service: "/terms"
  Contact Us: "/contact"

# Extra CSS styles
style: |
  body {
    font-family: 'Open Sans', sans-serif;
    font-size: 18px;
    line-height: 1.6;
    color: #333;
    background-color: #fff;
  }
  .container {
    max-width: 800px;
    margin: 0 auto;
  }
  .btn {
    display: inline-block;
    padding: 12px 24px;
    background-color: #007bff;
    color: #fff;
    font-weight: bold;
    border-radius: 4px;
    text-decoration: none;
    transition: all 0.3s ease;
  }
  .btn:hover {
    background-color: #0062cc;
  }
