# Site settings
title: "My Awesome Book"
description: "A website to showcase my new boo"
url: "https://fasih0001.github.io/"
baseurl: ""

# Theme settings
theme: jekyll-theme-cayman

# Navigation menu
navbar_links:
  Home: "/"
  About: "/about"
  Blog: "/blog"
  Contact: "/contact"

# Social links
social_links:
  Twitter: "https://twitter.com/username"
  GitHub: "https://github.com/username"
  LinkedIn: "https://linkedin.com/in/username"

# Footer
footer_links:
  Privacy Policy: "/privacy"
  Terms of Service: "/terms"
  Contact Us: "/contact"

